from __future__ import annotations

from dataclasses import dataclass

import torch

from n2wos.wos.directions import sample_unit_directions


@dataclass
class ExternalPointCharges:
    """Harmonic manufactured solution generated by external point charges.

    u(x) = sum_k weight_k / ||x - center_k||.

    If all centers lie outside the unit ball, u is harmonic inside the ball.
    Boundary data is obtained by evaluating the same analytic function on the
    unit sphere. This gives an exact reference for bias measurements.
    """

    centers: torch.Tensor
    weights: torch.Tensor

    @property
    def dim(self) -> int:
        return int(self.centers.shape[-1])

    def to(self, *, device: torch.device | str | None = None, dtype: torch.dtype | None = None):
        centers = self.centers
        weights = self.weights
        if device is not None or dtype is not None:
            centers = centers.to(device=device, dtype=dtype)
            weights = weights.to(device=device, dtype=dtype)
        return ExternalPointCharges(centers=centers, weights=weights)

    def true_solution(self, x: torch.Tensor) -> torch.Tensor:
        diff = x[:, None, :] - self.centers[None, :, :]
        r = torch.linalg.norm(diff, dim=-1).clamp_min(1.0e-30)
        return (self.weights[None, :] / r).sum(dim=-1)

    def boundary_value(self, y: torch.Tensor) -> torch.Tensor:
        return self.true_solution(y)


def make_external_point_charges(
    *,
    dim: int = 3,
    n_sources: int = 8,
    source_radius: float = 1.18,
    weight_scale: float = 0.25,
    seed: int = 7,
    device: torch.device | str = "cpu",
    dtype: torch.dtype = torch.float32,
) -> ExternalPointCharges:
    """Create a deterministic external-charge harmonic benchmark."""
    device = torch.device(device)
    gen = torch.Generator(device=device) if device.type == "cuda" else torch.Generator()
    gen.manual_seed(int(seed))
    dirs = sample_unit_directions(n_sources, dim, device=device, dtype=dtype, generator=gen)
    centers = dirs * float(source_radius)

    raw = torch.randn(n_sources, device=device, dtype=dtype, generator=gen)
    raw = raw - raw.mean()
    weights = weight_scale * raw / raw.std(unbiased=False).clamp_min(1.0e-12)
    return ExternalPointCharges(centers=centers, weights=weights)
